#!/usr/bin/env bash
#
# test.sh — run a single Minirel test query end to end:
#           dbcreate  ->  minirel < query  ->  dbdestroy
#
# Usage:
#   ./test.sh [-p PREFIX] [-j NL|SM|HJ] [-k] <query>
#
#   <query>      a perf test name (e.g. scan_large  ->  tests/perf/scan_large)
#                or a path to a query file
#   -p PREFIX    label prepended to every log line, and the stem minirel uses
#                for perf log files (default: the query's name)
#   -j METHOD    join method passed to minirel: NL (default), SM, or HJ
#   -k           keep the scratch database instead of destroying it
#   -h           show this help
#
# Data for the perf tests is generated by `make data` (see tests/perf/README.md).
#
set -euo pipefail

# Locate the repo from this script's own path, so it runs from anywhere.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$ROOT/out"
QUERYDIR="$ROOT/tests/"
DBCREATE="$OUT/dbcreate"
DBDESTROY="$OUT/dbdestroy"
MINIREL="$OUT/minirel"

PREFIX=""
JOIN="NL"
KEEP=0

usage() { sed -n '3,19p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while getopts ":p:j:kh" opt; do
  case "$opt" in
    p) PREFIX="$OPTARG" ;;
    j) JOIN="$OPTARG" ;;
    k) KEEP=1 ;;
    h) usage 0 ;;
    *) usage 1 ;;
  esac
done
shift $((OPTIND - 1))

[ $# -ge 1 ] || { echo "error: no query given" >&2; usage 1; }

# Resolve the query: a bare name means tests/perf/<name>, else treat it as a path.
if [ -r "$QUERYDIR/$1" ]; then
  QUERYFILE="$QUERYDIR/$1"
else
  QUERYFILE="$1"
fi
[ -r "$QUERYFILE" ] || { echo "error: cannot read query file: $QUERYFILE" >&2; exit 1; }

# The perf queries load data/*.data; nudge the user if it hasn't been generated.
if grep -q '\.\./data/' "$QUERYFILE" 2>/dev/null && [ ! -e "$ROOT/data/R_1k.data" ]; then
  echo "warning: perf data not found — run 'make data' first" >&2
fi

# Default the log prefix to the query's filename (e.g. "qu.3").
[ -n "$PREFIX" ] || PREFIX="$(basename "$QUERYFILE")"

case "$JOIN" in
  NL|SM|HJ) ;;
  *) echo "error: -j must be NL, SM, or HJ (got '$JOIN')" >&2; exit 1 ;;
esac

# Every line this script emits — its own messages and the DB tools' output —
# goes through here, so a run is fully labelled and greppable by its prefix.
log()    { printf '[%s] %s\n' "$PREFIX" "$*"; }
tagged() { sed "s/^/[$PREFIX] /"; }

for b in "$DBCREATE" "$MINIREL" "$DBDESTROY"; do
  [ -x "$b" ] || { log "missing binary: $b  (run 'make' first)"; exit 1; }
done

# A filename-safe form of the prefix, reused for the scratch DB and log paths.
SAFE="$(printf '%s' "$PREFIX" | tr -c 'A-Za-z0-9_.-' '_')"

# The scratch DB must be a sibling of data/ so the queries' "../data/..." paths
# resolve once minirel chdir's into it. The repo root is that sibling.
DB="$ROOT/_testdb_$SAFE"
DBNAME="$(basename "$DB")"

# Absolute log-path stem handed to minirel. It must be absolute because minirel
# chdir's into the (throwaway) DB dir; the measurement code appends suffixes to
# it, e.g. "<LOGPREFIX>_measure.csv".
LOGDIR="$ROOT/logs"
mkdir -p "$LOGDIR"
LOGPREFIX="$LOGDIR/$SAFE"

cleanup() {
  if [ "$KEEP" -eq 0 ] && [ -d "$DB" ]; then
    log "destroying $DBNAME"
    echo y | "$DBDESTROY" "$DB" >/dev/null 2>&1 || rm -rf "$DB"
  fi
}
trap cleanup EXIT

# Start from a clean slate (dbcreate refuses to mkdir over an existing dir).
[ -d "$DB" ] && { log "removing stale $DBNAME"; rm -rf "$DB"; }

log "creating $DBNAME"
"$DBCREATE" "$DB" 2>&1 | tagged

log "running $(basename "$QUERYFILE")  (join=$JOIN, logs=${LOGPREFIX}*)"
set +e
"$MINIREL" "$DB" "$JOIN" "$LOGPREFIX" < "$QUERYFILE" 2>&1 | tagged
status=${PIPESTATUS[0]}
set -e

# minirel returns 1 on a normal end-of-file (the query files have no `quit;`),
# so 0 and 1 both mean "ran to the end". A signal (>=128, e.g. an assert abort
# at 134) is a real crash and is reported as failure.
if [ "$status" -le 1 ]; then
  log "done — reached end of $(basename "$QUERYFILE")"
  exit 0
else
  log "minirel crashed (exit status $status)"
  exit "$status"
fi
